# A sample Gemfile
source "https://rubygems.org"

ruby "1.9.3"

group :cookbook do
  gem 'chef'
  gem 'knife-digital_ocean'
  gem 'knife-zero'
  gem 'berkshelf'
  gem 'chef-provisioning'
  gem 'chef-provisioning-fog'
end

group :cookbook, :test do
  gem 'chefspec'
  gem 'foodcritic'
  gem 'rubocop'
end
