name 'citizen_approved'
maintainer 'citizen_approved'
maintainer_email 'citizen_approved@citizen_approved'
license 'Apache 2.0'
description 'Installs/Configures citizen_approved'
version '0.1.1'

supports 'ubuntu'

depends 'apt'
depends 'build-essential'
depends 'database'
depends 'mysql'
depends 'nginx'
depends 'openssl'
depends 'rvm'

recipe 'citizen_approved::cluster', 'Installs a full citizen_approved cluster'
recipe 'citizen_approved::all', 'Installs a full stack citizen_approved server'
recipe 'citizen_approved::app', 'Installs a citizen_approved app server'
recipe 'citizen_approved::default', 'Base recipe to be applied on all servers'
recipe 'citizen_approved::mysql_master', 'Installs a mysql master'
